image: jdrouet/docker-with-buildx:stable

services:
  - name: docker:dind
    alias: dockerhost

variables:
  DOCKER_HOST: tcp://dockerhost:2375/
  DOCKER_DRIVER: overlay2
  DOCKER_TLS_CERTDIR: ""

build:
  stage: build
  before_script:
    - echo $'\r' >> ./src/main/resources/application.properties
    - echo "server.servlet.context-path=/$CI_PROJECT_NAME" >> ./src/main/resources/application.properties
  script:
    - docker context create dockerhost
    - docker buildx create --name multiarch-builder --use dockerhost
    - docker buildx inspect --bootstrap
    - docker buildx build --platform=linux/arm64/v8 --load -t $CI_REGISTRY_IMAGE .
    - docker login -u gitlab-ci-token -p $CI_JOB_TOKEN $CI_REGISTRY
    - docker push $CI_REGISTRY_IMAGE
  only:
    - main